let models = [
  "ActionState",
  "Address",
  "AgeLevel",
  "BuildingDimensionDetail",
  "BuildingEnvelopMaterial",
  "BusinessField",
  "Certificate",
  "Child",
  "ConstructionRelatedService",
  "ConstructionResource",
  "ConstrutionResourceQuantityPrice",
  "ContactPerson",
  "Department",
  "EducationStatus",
  "ElectricTower",
  "EmployeeAge",
  "EmployeeEducation",
  "ExperienceLevel",
  "FamilyStatus",
  "File",
  "GeneratingCapacity",
  "Graduate",
  "HydroElectricDam",
  "IrrigationCapacity",
  "JobExperience",
  "Ownership",
  "Permission",
  "Photo",
  "Port",
  "Position",
  "Project",
  "ProjectBond",
  "ProjectCategory",
  "ProjectDocument",
  "ProjectFile",
  "ProjectFinance",
  "ProjectPlan",
  "ProjectStakeholder",
  "ProjectStatus",
  "ProjectSubcategory",
  "ProjectTime",
  "ProjectType",
  "ProjectUsedResource",
  "ProjectVariation",
  "Railway",
  "RailwayStation",
  "ReferenceDocument",
  "Regulation",
  "RegulationDocument",
  "ResearchDocument",
  "ReservoirInfo",
  "Resource",
  "ResourceCategory",
  "ResourceSubcategory",
  "ResourceType",
  "RoadInfo",
  "RoadLayer",
  "RoadSegment",
  "Role",
  "RolePermission",
  "SolarEnergy",
  "SpillwayInfo",
  "StakeCategory",
  "Stakeholder",
  "StakeholderInfo",
  "StakeholderService",
  "StakeholderStudyField",
  "StakeholderType",
  "StakeSubcategory",
  "Status",
  "StudyField",
  "StudyLevel",
  "StudyPeriodCost",
  "StudyProgram",
  "Telecom",
  "TotalEmployee",
  "Training",
  "Transformer",
  "TransformerType",
  "TransmissionType",
  "TransmissionLine",
  "TurbineInfo",
  "User",
  "UserEmail",
  "UserPhone",
  "UserPosition",
  "WaterIrrigationDam",
  "WindEnergy",
  "WorkExperience",
  "ModelMenu",
  "Note",
  "Reply",
  "Specification",
  "Brand",
  "ResourceDetailType",
  "Salary"
];


let modules = [
  "MASTER",
  "PROJECT",
  "STAKEHOLDER",
  "DOCUMENT",
  "RESOURCE",
  "CENTER",
  // "analysis"
  // analysis can be further classified as project, stakeholder...
];

let permissionModules = [
  "projectmaster",
  "stakeholdermaster",
  "documentmaster",
  "resourcemaster",
  "generalmaster",
  "document",
  "resource",
  "stakeholderinfo",
  "stakeholderemployee",
  "stakeholderspecific",
  "stakeholderproject",
  "stakeholderfile",
  "projectinfo",
  "projecttime",
  "projectfinance",
  "projectstakeholder",
  "projectfile",
  "projectplan",
  "projectusedresource",
  "projectreport",
  "other",
  //forcenter
  "department",
  "position",
  "professional",
];
let roleName = [
  "Admin",
  "Register",
  "Checker",
  "Approver",
  "Authorizer",
  "Viewer",
];
let actions = ["register", "check", "approve", "authorize", "view"];

const modulemodels = {
  master: [
    "projectmaster",
    "stakeholdermaster",
    "documentmaster",
    "resourcemaster",
    "generalmaster",
  ],
  project: [
    "buildingdimensiondetail",
    "buildingenvelopmaterial",
    "electrictower",
    "generatingcapacity",
    "hydroelectricdam",
    "irrigationcapacity",
    "port",
    "railway",
    "railwaystation",
    "reservoirinfo",
    "roadinfo",
    "roadlayer",
    "roadsegment",
    "solarenergy",
    "spillwayinfo",
    "transformer",
    "transformertype",
    "transmissionline",
    "turbineinfo",
    "waterirrigationdam",
    "windenergy",
    "telecom",
  ],

  stakeholder: [
    "studyfield",
    "studyperiodcost",
    "graduate",
    "stakeholderservice",
    "constructionrelatedservice",
  ],
  resource: [
    "specification",
    "brand",
    "resourcetype",
    "resourcequantityandprice",
    "studyfield",
    "studylevel",
    "workexperience",
    "salary"
  ],
  document: [
    "document"
  ],
  center: [
    "department", 
    "position", 
    "professional"
  ],
};

const mainanalysismodules = {
  project: [
    "Project", 
    "ProjectType", 
    "ProjectCategory", 
    "ProjectSubCategory"
  ],
  stakeholder: [
    "Stakeholder", 
    "StakeholderType", 
    "StakeholderCategory", 
    "StakeholderSubCategory"
  ],
  document: [
    "Document", 
    "DocumentType", 
    "DocumentCategory", 
    "DocumentSubCategory"
  ],
  resource: [
    "Resource", 
    "ResourceType", 
    "ResourceCategory", 
    "ResourceSubCategory"
  ],
};

module.exports = {
  models,
  modules,
  roleName,
  permissionModules,
  actions,
  modulemodels,
  mainanalysismodules,
};
