let models = [
  "ActionState",
  "Address",
  "AgeLevel",
  "BuildingDimensionDetail",
  "BuildingEnvelopMaterial",
  "BusinessField",
  "Certificate",
  "Child",
  "ConstructionRelatedService",
  "ConstructionResource",
  "ConstrutionResourceQuantityPrice",
  "ContactPerson",
  "Department",
  "EducationStatus",
  "ElectricTower",
  "EmployeeAge",
  "EmployeeEducation",
  "ExperienceLevel",
  "FamilyStatus",
  "File",
  "GeneratingCapacity",
  "Graduate",
  "HydroElectricDam",
  "IrrigationCapacity",
  "JobExperience",
  "Ownership",
  "Permission",
  "Photo",
  "Port",
  "Position",
  "Project",
  "ProjectBond",
  "ProjectCategory",
  "ProjectDocument",
  "ProjectFile",
  "ProjectFinance",
  "ProjectPlan",
  "ProjectStakeholder",
  "ProjectStatus",
  "ProjectSubcategory",
  "ProjectTime",
  "ProjectType",
  "ProjectUsedResource",
  "ProjectVariation",
  "Railway",
  "RailwayStation",
  "ReferenceDocument",
  "Regulation",
  "RegulationDocument",
  "ResearchDocument",
  "ReservoirInfo",
  "Resource",
  "ResourceCategory",
  "ResourceSubcategory",
  "ResourceType",
  "RoadInfo",
  "RoadLayer",
  "RoadSegment",
  "Role",
  "RolePermission",
  "SolarEnergy",
  "SpillwayInfo",
  "StakeCategory",
  "Stakeholder",
  "StakeholderInfo",
  "StakeholderService",
  "StakeholderStudyField",
  "StakeholderType",
  "StakeSubcategory",
  "Status",
  "StudyField",
  "StudyLevel",
  "StudyPeriodCost",
  "StudyProgram",
  "Telecom",
  "TotalEmployee",
  "Training",
  "Transformer",
  "TransformerType",
  "TransmissionType",
  "TransmissionLine",
  "TurbineInfo",
  "User",
  "UserEmail",
  "UserPhone",
  "UserPosition",
  "WaterIrrigationDam",
  "WindEnergy",
  "WorkExperience",
  "ModelMenu",
  "Note",
  "Reply",
  "Specification",
  "Brand",
  "ResourceDetailType",
  "Salary"
];


let modules = [
  "MASTER",
  "PROJECT",
  "STAKEHOLDER",
  "DOCUMENT",
  "RESOURCE",
  "CENTER",
  // "analysis"
  // analysis can be further classified as project, stakeholder...
];

let permissionModules = [
  "projectmaster",
  "stakeholdermaster",
  "documentmaster",
  "resourcemaster",
  "generalmaster",
  "document",
  "resource",
  "stakeholderinfo",
  "stakeholderemployee",
  "stakeholderspecific",
  "stakeholderproject",
  "stakeholderfile",
  "projectinfo",
  "projecttime",
  "projectfinance",
  "projectstakeholder",
  "projectfile",
  "projectplan",
  "projectusedresource",
  "projectreport",
  "other",
  //forcenter
  "department",
  "position",
  "professional",
];
let roleName = [
  "Admin",
  "Register",
  "Checker",
  "Approver",
  "Authorizer",
  "Viewer",
];
let actions = ["register", "check", "approve", "authorize", "view"];

const modulemodels = {
  master: [
    "projectmaster",
    "stakeholdermaster",
    "documentmaster",
    "resourcemaster",
    "generalmaster",
  ],
  project: [
    "buildingdimensiondetail",
    "buildingenvelopmaterial",
    "electrictower",
    "generatingcapacity",
    "hydroelectricdam",
    "irrigationcapacity",
    "port",
    "railway",
    "railwaystation",
    "reservoirinfo",
    "roadinfo",
    "roadlayer",
    "roadsegment",
    "segmentgeometry",
    "solarenergy",
    "spillwayinfo",
    "transformer",
    "transformertype",
    "transmissionline",
    "turbineinfo",
    "waterirrigationdam",
    "windenergy",
    "telecom",
    "trafficparameter",
    "intersectiondriveway",
    "accessory",
    "pavement",
    "culvertbasicdata",
    "culvertstructuralinformation",
    "culvertroadoverinformation",
    "bridgebasicdata",
    "bridgeareadata",
    "bridgesuperstructure",
    "bridgesubstructure",
    "bridgefoundation",
    "bridgeinspection",
    "bridgestructureinformation",
    "trafficvolume",
    "roadprojectqualitycontrol",
    "roaddrainage",
    "drainageassessment",
    "roadsurfacecondition",
    "maintenancehistory",
    "environmentaldata",
    "roadmaintenancedata",
    "roadmaintenanceactivity",
    "geotechnicalinformation",
    "safetyandhealth",

    "telecominfrastructurecomponent",
    "telecominfrastructureage",
    "maintenance",
    "networkcapacity",
    "networkcoverage",

    "mobilenetwork",
    "satellitenetwork",
    "satelliteinfrastructureage",
    "satellitenetworkcomponentmanufacturer",
    "internetconnection",
    "mobilenetworkcomponentage",
    "internetconnectioninfrastructureage",
    "internetconnectioninfrastructuremanufacturer",
    "broadcastinginfrastructure",
    "broadcastinginfrastructureage",
    "broadcastinginfrastructureage",
    "broadcastinginfrastructuremanufacturer",
    "datacenter",
    "datacentercomponentage",
    "datacentercomponentmanufacturer",
    "datacenterfacilitycapacity",
    "environmentalcontrol",
    "powergenerationcapacity",
    "hydrologicalinformation",
    "dam",
    "transmission",
    "reliabilityandmaintenance",
    "environmentalandsocialimpact",
    "regulationandpolicy",
    "windresource",
    "windturbine",
    "solarResourceinformation",
    "solarpanel",
    "geothermalpowerwell",
    "geothermalpowerinfrastructure",
    
    "transmissionlineinformation",
    "transmissionlineconductorandtowerdata",
    "transmissionlineequipmentdata",
    "substationtransformerandswitchgeardata",
    "substationlayoutandcommunicationdata",
    "minigridstation",
    "minigridstationdistributionline",
    "minigridstationconsumer",
    "minigridstationbackuppowersource",
    "minigridstationdistributionlineinfrastructure",
    "electricdistributiontransformer",
    "electricdistributiontransformertype",
    "electricsmartmetersdata",
    "electricsmartmetersratingsdata",
    "electricsmartmetersperformancedata",
    "generalairportinformation",
    "runwayandapproachdata",
    "terminalandfacilitydata"
  ],

  stakeholder: [
    "stakeholderstudyfield",
    "studyperiodcost",
    "graduate",
    "stakeholderservice",
    "constructionrelatedservice",
  ],
  resource: [
    "specification",
    "brand",
    "resourcetype",
    "resourcequantityandprice",
    "studyfield",
    "studylevel",
    "workexperience",
    "salary"
  ],
  document: [
    "document"
  ],
  center: [
    "department", 
    "position", 
    "professional"
  ],
};

const mainanalysismodules = {
  project: [
    "Project", 
    "ProjectType", 
    "ProjectCategory", 
    "ProjectSubCategory"
  ],
  stakeholder: [
    "Stakeholder", 
    "StakeholderType", 
    "StakeholderCategory", 
    "StakeholderSubCategory"
  ],
  document: [
    "Document", 
    "DocumentType", 
    "DocumentCategory", 
    "DocumentSubCategory"
  ],
  resource: [
    "Resource", 
    "ResourceType", 
    "ResourceCategory", 
    "ResourceSubCategory"
  ],
};


  const projectmastermodels = [
    "FunctionalClassification",
    "DesignClassification",
    "DesignStandard",
    "DesignTrafficFlow",
    "SurfaceType",
    "CrossSectionType",
    "IntersectionType",
    "DrivewayAccessPoint",
    "PedestrianFacility",
    "RoadLengthType",
    "AreaTopography",
    "PierType",
    "AbutmentType",
    "EndwallTypeInlet",
    "EndwallTypeOutlet",
    "PavedWaterWayType",
    "SoilType",
    "GuardRailType",
    "BridgeStructureType",
    "SpanSupportType",
    "DeckSlabType",
    "ExpansionJointType",
    "BridgePartDefect",
    "DamageType",
    "DamageCondition",
    "HydrologyDefect",
    "RoadSafetyFeature",
    "CountType",
    "ProjectPhase",
    "InspectionType",
    "CurrentCondition",
    "GroundWaterImpact",
    "SlopeStability",
    "MaintenanceFrequency",
    "MaintenanceType",
    "DrainageType",
    "DrainageCondition",
    "AssessmentCondition",
    "SeverityLevel",
    "SuggestedRepair",
    "RecommendedActionUrgency",
    "HazardType",
    "PotentialImpact",
    "RiskLevel",
    "IncidentType",
    "IncidentTime"
  ]

const moduletypes = {
  projects: [
    "Building",
    "Road",
    "Telecommunication",
    "Electric power",
    "Water Infrastructure",
    "Railway",
    "Air field/ Air port"
  ],
  resource: [
    "Building",
    "Road",
    "Telecommunication",
    "Electric power",
    "Water Infrastructure",
    "Railway",
    "Air field/ Air port",
    "Materials",
    "Machinery and Equipment",
    "Minerals",
    "Professionals"
  ]
  
}

module.exports = {
  models,
  modules,
  roleName,
  permissionModules,
  actions,
  modulemodels,
  mainanalysismodules,
  projectmastermodels,
  moduletypes
};
